path:
    raw: "../../data/raw/"
    interim: "../../data/interim/"
    processed: "../../data/processed/"
    artifact: "../../artifacts/"
    udf: "../../src"
    
path-make:
    raw: "data/raw/"
    interim: "data/interim/"
    processed: "data/processed/"
    artifact: "artifacts/"
    udf: "src/"