# fig, ax = plt.subplots(6, 2, figsize = (15, 13))
# sns.boxplot(x= df_cars["mpg"], ax = ax[0,0])
# sns.distplot(df_cars['mpg'], ax = ax[0,1])
# sns.boxplot(x= df_cars["cylinders"], ax = ax[1,0])
# sns.distplot(df_cars['cylinders'], ax = ax[1,1])
# sns.boxplot(x= df_cars["displacement"], ax = ax[2,0])
# sns.distplot(df_cars['displacement'], ax = ax[2,1])
# sns.boxplot(x= df_cars["horsepower"], ax = ax[3,0])
# sns.distplot(df_cars['horsepower'], ax = ax[3,1])
# sns.boxplot(x= df_cars["weight"], ax = ax[4,0])
# sns.distplot(df_cars['weight'], ax = ax[4,1])
# sns.boxplot(x= df_cars["acceleration"], ax = ax[5,0])
# sns.distplot(df_cars['acceleration'], ax = ax[5,1])
# plt.tight_layout()